---

- name: restart httpd
  service: name=httpd state=restarted

- name: restart zabbix-server
  service: name=zabbix-server state=restarted

- name: restart mysql
  service: name=mysqld state=restarted

- name: import zabbix data
  mysql_db: name={{ zabbix_dbname }} state=import target=/usr/share/zabbix-mysql/schema.sql
  mysql_db: name={{ zabbix_dbname }} state=import target=/usr/share/zabbix-mysql/images.sql
  mysql_db: name={{ zabbix_dbname }} state=import target=/usr/share/zabbix-mysql/data.sql
